name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js 24.x
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              uses: Forsakringskassan/prettier-config@28e862ba90334b5bed60c46ba2442fa25099b830 # v3.6.1
