name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js 24.x
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              uses: Forsakringskassan/prettier-config@a5a8b5f4f783ba2524b87fc8c8b78ebebc02bc23 # v3.6.2
