name: Lint

on: [push, pull_request]

permissions:
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js 24.x
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
            - name: Install dependencies
              run: npm ci
            - name: Prettier
              uses: Forsakringskassan/prettier-config@4d7e1f6522f59d92979a1fc2b0c0c5c5c26a6a4b # v3.7.1
